// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/survivor-hub/Chyme.tsx": () => import("../components/mockups/survivor-hub/Chyme.tsx"),
  "./components/mockups/survivor-hub/ChymeApp.tsx": () => import("../components/mockups/survivor-hub/ChymeApp.tsx"),
  "./components/mockups/survivor-hub/Desktop.tsx": () => import("../components/mockups/survivor-hub/Desktop.tsx"),
  "./components/mockups/survivor-hub/MobileChyme.tsx": () => import("../components/mockups/survivor-hub/MobileChyme.tsx"),
  "./components/mockups/survivor-hub/MobileHome.tsx": () => import("../components/mockups/survivor-hub/MobileHome.tsx")
};
